apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.appName }}-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
    component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.global.appName }}
      component: backend
  template:
    metadata:
      labels:
        app: {{ .Values.global.appName }}
        component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: 8000
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.appName }}-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
    component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
  selector:
    app: {{ .Values.global.appName }}
    component: backend 