apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.appName }}-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
    component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}

  # Rolling update strategy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: {{ .Values.global.appName }}
      component: backend

  template:
    metadata:
      labels:
        app: {{ .Values.global.appName }}
        component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: 8000

          # Health checks
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.appName }}-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
    component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
  selector:
    app: {{ .Values.global.appName }}
    component: backend
