apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.appName }}-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}

  # Rolling update strategy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: {{ .Values.global.appName }}
      component: frontend

  template:
    metadata:
      labels:
        app: {{ .Values.global.appName }}
        component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"

          # Environment variable
          env:
            - name: REACT_APP_API_URL
              value: "{{ .Values.frontend.env.REACT_APP_API_URL }}"

          ports:
            - containerPort: 80

          # Health checks
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.appName }}-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
    component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  {{- if .Values.frontend.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.frontend.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
  selector:
    app: {{ .Values.global.appName }}
    component: frontend
