apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-backend
  labels:
    app: {{ include "my-app.name" . }}
    component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    app: {{ include "my-app.name" . }}
    component: backend

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-frontend
  labels:
    app: {{ include "my-app.name" . }}
    component: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "my-app.name" . }}
    component: frontend 